package Tests;

import org.junit.jupiter.api.*;

import DTOs.SuppliersModuleDTOs.BillofQuantitiesItemDTO;
import Suppliers.DataLayer.DAOs.DataAccessException;
import Suppliers.DataLayer.DAOs.JdbcBillofQuantitiesItemsDAO;
import Suppliers.DataLayer.Interfaces.BillofQuantitiesItemDAOInterface;
import Suppliers.DataLayer.util.Database;

import java.sql.SQLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class JdbcBillofQuantitiesItemDAOTest {
   private BillofQuantitiesItemDAOInterface dao;

   @BeforeEach
   void setUp() throws SQLException {
      Database.setDB_URL(Database.DB_TEST_URL);
      Database.seedDefaultData();
      dao = new JdbcBillofQuantitiesItemsDAO();
   }

   @AfterEach
   void tearDown() throws SQLException {
      Database.deleteAllData();
   }

   @Test
   void insertAndFetchItems_roundTrip() throws SQLException {
      // Arrange: suppose agreement_id=1 already exists in the seeded test database.
      BillofQuantitiesItemDTO toInsert = new BillofQuantitiesItemDTO(
            /* agreementId = */ 1,
            /* lineInBillId = */ -1,
            /* productName = */ "Widget A",
            /* productId = */ 1,
            /* quantity = */ 10,
            /* discountPercent = */ new java.math.BigDecimal("5.00"));

      // Act: insert and fetch new line
      BillofQuantitiesItemDTO created = dao.createBillofQuantitiesItem(toInsert);
      assertNotNull(created, "Created BOQ item should not be null");
      assertTrue(created.getLineInBillID() > 0, "LineInBillID should be autogenerated and > 0");

      List<BillofQuantitiesItemDTO> all = dao.getAllBillofQantitiesItemsForAgreementId(1);
      assertFalse(all.isEmpty(), "Should retrieve at least the one we just inserted");

      boolean found = all.stream()
            .anyMatch(item -> item.getProductId() == created.getProductId() &&
                  item.getQuantity() == created.getQuantity());
      assertTrue(found, "The inserted item should appear in the list by agreementId");
   }

   @Test
   void insertingWithNullQuantity_throwsSQLException() {
      // quantity is NOT NULL and >0, so setting 0 or negative should fail
      BillofQuantitiesItemDTO bad = new BillofQuantitiesItemDTO(
            /* agreementId = */ 1,
            /* lineInBillId = */ -1,
            /* productName = */ "Bad Widget",
            /* productId = */ 1,
            /* quantity = */ 0,
            /* discountPercent = */ new java.math.BigDecimal("5.00"));
      assertThrows(DataAccessException.class, () -> dao.createBillofQuantitiesItem(bad),
            "Inserting a BOQ item with quantity=0 should violate CHECK(quantity>0)");
   }
}