package PresentationLayer.GUI.SupplierScreen.Controllers;

import java.math.BigDecimal;

import DTOs.SuppliersModuleDTOs.SupplierProductDTO;
import DomainLayer.SystemFactory;
import ServiceLayer.SuppliersServiceSubModule.SupplierService;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class SupplierProductAddController {

   @FXML
   private TextField catalogField;
   @FXML
   private TextField nameField;
   @FXML
   private TextField priceField;
   @FXML
   private TextField weightField;
   @FXML
   private TextField expiresField;
   @FXML
   private TextField manufacturerField;

   private SystemFactory systemFactory = new SystemFactory();
   private SupplierService supplierService = systemFactory.getSupplierModule().getSupplierService();
   private int supplierId;

   /** Inject service & supplier ID before showing dialog */
   public void init(int supplierId) {
      this.supplierId = supplierId;
   }

   @FXML
   private void onSave() {
      try {
         var dto = new SupplierProductDTO(
               supplierId,
               -1, // productId is generated by backend
               catalogField.getText().trim(),
               nameField.getText().trim(),
               new BigDecimal(priceField.getText().trim()),
               new BigDecimal(weightField.getText().trim()),
               Integer.parseInt(expiresField.getText().trim()),
               manufacturerField.getText().trim());

         var resp = supplierService.addProductToSupplier(dto, supplierId);
         if (resp.isSuccess()) {
            closeDialog();
         } else {
            showError(String.join("\n", resp.getErrors()));
         }
      } catch (Exception e) {
         showError("Invalid input: " + e.getMessage());
      }
   }

   @FXML
   private void onCancel() {
      closeDialog();
   }

   private void closeDialog() {
      Stage stage = (Stage) catalogField.getScene().getWindow();
      stage.close();
   }

   private void showError(String msg) {
      new Alert(Alert.AlertType.ERROR, msg).showAndWait();
   }
}